### ISSUE TITLE
0.4.0 is broken

### ISSUE THREAD

**Issue by saiichihashimoto** [joaocarmo/i18n-postal-address#13] opened 2020-11-13 18:27 UTC
After updating to 0.4.0 from 0.3.0, now my builds have an issue with this package:

![image](https://user-images.githubusercontent.com/2819256/99107366-5a53aa80-25ab-11eb-8b82-0c3f18c3331b.png)

It likely has something to do with https://github.com/joaocarmo/i18n-postal-address/compare/v0.3.0...v0.4.0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R7, but I don't understand how this works well enough to point to the issue.

**Comment by joaocarmo** [comment] 2020-11-13 18:44
@saiichihashimoto , can you share a bit of your code? How are you importing the module? I can't seem to reproduce this issue.

**Comment by saiichihashimoto** [comment] 2020-11-13 19:40
![image](https://user-images.githubusercontent.com/2819256/99114013-c3402000-25b5-11eb-9c8b-b27f61133587.png)
![image](https://user-images.githubusercontent.com/2819256/99114040-cfc47880-25b5-11eb-986f-b0e0c7c0c49e.png)

**Comment by joaocarmo** [comment] 2020-11-13 19:58
@saiichihashimoto thank you for sharing! Everything seems alright... What's the node version on your system?

**Comment by saiichihashimoto** [comment] 2020-11-13 20:00
![image](https://user-images.githubusercontent.com/2819256/99115764-8a557a80-25b8-11eb-8e3b-33aaed1a6063.png)

**Comment by joaocarmo** [comment] 2020-11-13 20:16
@saiichihashimoto , can you try removing the lock file and re-installing the dependencies?

```sh
# Yarn
rm yarn.lock && yarn install

# npm
rm package-lock.json &&  npm install
```

If that doesn't work, try removing the `engines` key from your `package.json` file or changing it to:

```json
"engines": {
    "node": ">=12",
    "npm": "6.14.6"
}
```

**Comment by saiichihashimoto** [comment] 2020-11-13 22:40
I removed my package-lock and reinstalled, and the failure remained. For environment reasons I need to stay on node version 12.0, does 0.4.0 not work for 12 anymore?

**Comment by joaocarmo** [comment] 2020-11-14 11:07
I can't think of a reason why that should be a problem. I recently changed the `package.json` to include an `exports` directive for better usage as an ESM module and that might be in conflict with the `engines` directive. Try removing that and see if it works. Edit the following file and remove the `exports` key entry:

```txt
node_modules/i18n-postal-address/package.json
```

If that works, you can make the changes permanent with [patch-package](https://www.npmjs.com/package/patch-package).

**Comment by saiichihashimoto** [comment] 2020-11-19 18:32
patch-package helps me avoid a problem, not solve it, correct? We should figure out a more long term solution that works here.

**Comment by joaocarmo** [comment] 2020-11-23 09:42
This is more of a configuration issue which `patch-package` can resolve easily.

I'll close this issue for now.

**Closed by joaocarmo** 2020-11-23 09:42 UTC
Labels: question

**Comment by saiichihashimoto** [comment] 2020-12-09 19:06
I don't understand how a consumer's ability to rewrite the package means the issue is resolved. `patch-package` exists to fix _broken_ node modules, indicating that the package is broken, not working-as-intended.

![image](https://user-images.githubusercontent.com/2819256/101675104-fb087f00-3a1e-11eb-9564-ed78eeeabd49.png)

I would label this as `wont-fix` since that's more accurate.

**Comment by joaocarmo** [comment] 2020-12-15 22:36
@saiichihashimoto , you are correct and I've labeled this as `wontfix` for now.

The reason behind my decision is that the recent changes makes the package more compatible with modern distribution channels such as CDNs.

It's unfortunate that it might break your application but, since it's due to a very particular configuration within your project, I believe `patch-package` is a good solution. It allows you to keep receiving the latest version without having to change anything.

Even though it might be described as a helper for _broken_ packages, it also allows you to customize packages without having to fork them — which then would require you to maintain the fork to keep up with the updates.

**Comment by saiichihashimoto** [comment] 2020-12-16 01:24
Just for context, I am using [next.js](https://nextjs.org/) which handles a significant part of the build process, including what's conflicting with this version. It is a specific way of configuring a project but I would definitely not consider it an outlier considering its wide adoption. My solution will be to stick with `0.3.0` since I would like to avoid patch-package.

**Comment by joaocarmo** [comment] 2020-12-21 14:54
That's great to have documented, thanks for sharing your information!

Regarding your original issue (#11), since `v.0.4.0` only adds custom formats, you can pass `useTransforms: false` in the [options](https://github.com/joaocarmo/i18n-postal-address#options) and it will not apply any transforms — that means no capitalisation.

**Comment by hubcards** [comment] 2021-02-03 13:21
Same Problem, same Environment. Just wanted to emphasize that this is a standard Next.js/Vercel Scenario.

**Comment by joaocarmo** [comment] 2021-02-03 21:16
@hubcards which version are you using? **TypeScript** or plain **JavaScript**?
